{{- if .Values.argocd.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-app-repo-creds
  namespace: argocd
spec:
  refreshInterval: "1h" # Periodically checks AWS for key rotations
  secretStoreRef:
    name: aws-secretsmanager-store
    kind: ClusterSecretStore
  target:
    name: github-app-repo-creds # The native secret created by ESO
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      stringData:
        url: {{ .Values.argocd.repoUrl | quote }}
        type: "git"
        githubAppID: {{ .Values.argocd.appID | quote }}
        githubAppInstallationID: {{ .Values.argocd.installationID | quote }}
        # Pulls the raw PEM contents from AWS into the exact key name Argo expects
        githubAppPrivateKey: "{{ .private_key }}"
  data:
    - secretKey: private_key
      remoteRef:
        key: {{ .Values.argocd.secretName | quote }}
{{- end }}
