apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.region }}
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager-store
  namespace: external-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.region }}
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager-store
  namespace: argocd
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.region }}
