apiVersion: v2
name: external-secrets-defaults
description: Default External Secrets Operator SecretStores and ClusterSecretStores for AWS Secrets Manager
type: application
version: 0.1.0
appVersion: "1.0.0"
